debug: false
logging:
  group:
    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
  level:
    root: WARN
    tomcat: ERROR
    web: DEBUG
    org.hibernate: ERROR
    org.springframework.data: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 2
  file:
    path: /tmp
spring:
  datasource:
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    username: default
    password:
    url: jdbc:ch://192.168.2.101:18123/default
    connectionTimeout: 67000
    hikari:
      connectionTimeout: 67000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true